### ISSUE TITLE
EDI Schema Reference sometimes leads to 404 pages

### ISSUE THREAD

**Issue by akasparas** [hellooops/vscode-edi-support#2]
EDI Schema Reference sometimes (not always) leads to 404 pages

For example hovering over UMB in text
UNB+UNOA:2+4770079000008:14+5720005400017:14+230926:1731+S381888++++1++0'
Produces URL bellow:
https://www.kasoftware.com/schema/edi/edifact/D01B/segments/UNB/

It produces Page not found error. 
What else produces these errors you probably could find in your web server's logs.

**Comment by hellooops** [comment]
Thanks for pointing out this, I'll check this.

**Comment by hellooops** [comment]
Currently, there are no definitions in the EDIFACT schema files for UNA/UNB/UNZ/UNT and the related elements These segments and elements are merely mocked up. So the "EDI Schema Reference" page cannot be found on the website.

As a temporary workaround, I have removed the "EDI Schema Reference" link when hovering over the 4 segments and their elements. Once the information for these 4 segments is added to the schema files, the links will be restored.
