### ISSUE TITLE
How to change default Edifact version

### ISSUE THREAD

**Issue by EloToJaa** [hellooops/vscode-edi-support#4]
How can I change default Edifact from D97A to for example D01B?

I would like this code to not show invalid code value.
Code 100 is not added to available values in D97A
```
DTM+100:20201015:102'
```

**Comment by hellooops** [comment]
Can you paste the entire edifact message here? So I can exactly reproduce the issue.

**Comment by hellooops** [comment]
Try changing the 96A in UNH segment to 01B.
![image](https://github.com/hellooops/vscode-edi-support/assets/41995968/e73dea96-75cd-4bcd-881f-878f29983e31)
![image](https://github.com/hellooops/vscode-edi-support/assets/41995968/2a6cb53e-ff72-4d51-ba58-fcbbb98b842f)

**Comment by EloToJaa** [comment]
You are right my bad.
I did not notice UNH.
I am new to this format.
Thanks for your help
