### ISSUE TITLE
prettify and minify command not found

### ISSUE THREAD

**Issue by akasparas** [hellooops/vscode-edi-support#5]
I upgraded from v1.3.1 to v1.4.2 and pressing on prettify / minify icons I get message:
"command 'edi-support.prettify' not found" and "command 'edi-support.minify' not found" respectibly.

VS Code About:
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:16:23.416Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.8.0-31-generic

**Comment by hellooops** [comment]
> I upgraded from v1.3.1 to v1.4.2 and pressing on prettify / minify icons I get message: "command 'edi-support.prettify' not found" and "command 'edi-support.minify' not found" respectibly.
> 
> VS Code About: Version: 1.89.1 Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685 Date: 2024-05-07T05:16:23.416Z Electron: 28.2.8 ElectronBuildId: 27744544 Chromium: 120.0.6099.291 Node.js: 18.18.2 V8: 12.0.267.19-electron.0 OS: Linux x64 6.8.0-31-generic

Please update the extension to the latest version to see if this issue still exists.
