### ISSUE TITLE
installation errors 

### ISSUE THREAD

**Issue by gabrielCharibPolls** [hellooops/vscode-edi-support#6]
Last Friday, I updated my Visual Studio Code along with the EDI Support plugin, and everything was working perfectly.

On Monday, while working remotely, everything was still functioning properly.

However, on Tuesday, when I turned on my PC, a message appeared indicating that Visual Studio Code had updated and the plugin no longer worked. A colleague tried to resolve the issue by downloading the VSIX installation file, but without success. I tried several older versions of the plugin as well as running with administrative rights, but the same message persists.
<img width="960" alt="mis" src="https://github.com/hellooops/vscode-edi-support/assets/110329448/28f89842-e1a9-455d-9135-930938e5769a">
<img width="182" alt="image" src="https://github.com/hellooops/vscode-edi-support/assets/110329448/c59a8c0f-57b6-459c-87bd-1c2cf0ac6633">
<img width="277" alt="image" src="https://github.com/hellooops/vscode-edi-support/assets/110329448/3fc077d4-44ca-4e77-90bd-21c310e277f2">

**Comment by hellooops** [comment]
Hi gabrielCharibPolls, please update your VSCode to the latest and try again.

The minimum VSCode version that EDI Support plugin supports is 1.78.0. While your VSCode version is 1.47.3 which is out of date, the latest VSCode version now is 1.89.1.
