### ISSUE TITLE
Define the semantic of individual Edifact extensions

### ISSUE THREAD

**Issue by klacol** [hellooops/vscode-edi-support#8]
Thanks for the great extension. It helps a lot to understand Edifact messages.

I am working with messages, that contain individual extensions. Eg.  i have such a line:

```edifact
FTX+Z02+++MP-ID Absender:NAD'
```

This is not valid, because the value ``Z02`` is an invalid code value for the qualifier 'Text subject code qualifier.

Is there a possibility, to extend the schema? I would like to be able to add somewhere the meaning of ``Z02`` and show it in VS Code.

**Comment by hellooops** [comment]
Hi klacol,

You can extend the schema by editing the schema file manually in vscode extension directory. 

E.g. 
1. Open C:\Users\xxx\.vscode\extensions\dericlee.edi-edifact-support-1.4.4-dev\out\schemas\edifact\D97A\RSSBus_D97A.json
2. Add code to "Qualifiers/Text subject qualifier"
![image](https://github.com/user-attachments/assets/2847dc39-ddee-43ef-9b52-f97d9a8e2a2e)

3. restart vscode
![image](https://github.com/user-attachments/assets/dfbf40c1-821d-48f6-b73d-34edc5297592)



Where are extensions installed?
Windows %USERPROFILE%\.vscode\extensions.
macOS ~/.vscode/extensions.
Linux ~/.vscode/extensions.
